"""
======================================================================
RECLAIM TREATMENT / CONTROL DATA AUDIT
======================================================================

Purpose
-------
Validate whether RECLAIM has a legitimate treatment/control experiment
that can be used for causal uplift modeling.

IMPORTANT
---------
This audit DOES NOT assign treatment.

Treatment assignment must already have happened during the simulation,
before recovery outcomes were generated.

Expected experiment columns
----------------------------
treatment
recovered
recovered_amount
intervention_cost
customer_friction_cost
net_recovered_value

Expected treatment meaning
---------------------------
treatment = 1 -> RECLAIM intervention
treatment = 0 -> control / no intervention
"""

from pathlib import Path
import sys
import numpy as np
import pandas as pd


# ======================================================================
# CONFIGURATION
# ======================================================================

PROJECT_ROOT = Path(r"D:\RECLAIM")

DATA_DIR = PROJECT_ROOT / "data" / "generated"

PREDICTION_FILE = DATA_DIR / "calibrated_recovery_predictions.csv"

# IMPORTANT:
# This is the experiment generated by the treatment/control simulator.
EXPERIMENT_FILE = DATA_DIR / "reclaim_treatment_control_experiment.csv"

# Legacy observational outcome file.
OUTCOME_FILE = DATA_DIR / "recovery_outcomes.csv"


FEATURES = [
    "amount",
    "payment_method",
    "failure_reason",
    "historical_transaction_count",
    "historical_success_rate",
    "historical_failure_count",
    "hours_since_previous_transaction",
    "previous_transaction_success",
    "transactions_last_7d",
    "successful_payments_last_7d",
    "failed_payments_last_7d",
    "avg_amount_last_7d",
    "failure_rate_last_7d",
    "amount_vs_recent_average",
    "payment_momentum",
    "failure_streak",
    "hours_since_last_success",
    "hours_since_last_failure",
    "method_share",
    "recoverability_score",
    "model_confidence",
    "base_recovery_probability",
]


# ======================================================================
# DISPLAY HELPERS
# ======================================================================

def header(title):
    print()
    print("=" * 70)
    print(title)
    print("=" * 70)


def section(title):
    print()
    print("=" * 70)
    print(title)
    print("=" * 70)


def passed(message):
    print(f"[PASS] {message}")


def warning(message):
    print(f"[WARN] {message}")


def failed(message):
    print(f"[FAIL] {message}")


def info(message):
    print(message)


def currency(value):
    if pd.isna(value):
        return "₹0.00"
    return f"₹{float(value):,.2f}"


def pct(value):
    if pd.isna(value):
        return "N/A"
    return f"{float(value):.2%}"


# ======================================================================
# FILE LOCATION
# ======================================================================

def locate_files():
    header("LOCATING DATA")

    print(f"Project root: {PROJECT_ROOT}")

    if not PROJECT_ROOT.exists():
        failed(f"Project root does not exist: {PROJECT_ROOT}")
        sys.exit(1)

    if PREDICTION_FILE.exists():
        passed(f"Prediction dataset found: {PREDICTION_FILE}")
    else:
        failed(f"Prediction dataset missing: {PREDICTION_FILE}")
        sys.exit(1)

    # The experiment file is the PRIMARY source for this audit.
    if EXPERIMENT_FILE.exists():
        passed(
            f"Treatment/control experiment found: {EXPERIMENT_FILE}"
        )
    else:
        failed(
            "Treatment/control experiment file is missing:\n"
            f"{EXPERIMENT_FILE}"
        )

        print()
        print("Run the treatment/control experiment simulator first.")
        print(
            "The audit will NOT create treatment/control assignments "
            "itself."
        )

        sys.exit(1)

    # Legacy outcome file is optional.
    if OUTCOME_FILE.exists():
        passed(f"Legacy outcome dataset found: {OUTCOME_FILE}")
    else:
        warning(
            f"Legacy outcome dataset not found: {OUTCOME_FILE}"
        )

    return PREDICTION_FILE, EXPERIMENT_FILE


# ======================================================================
# LOAD DATA
# ======================================================================

def load_data():
    prediction_file, experiment_file = locate_files()

    header("LOADING DATA")

    predictions = pd.read_csv(prediction_file)
    experiment = pd.read_csv(experiment_file)

    passed(f"Prediction rows: {len(predictions)}")
    passed(f"Experiment rows: {len(experiment)}")

    return predictions, experiment


# ======================================================================
# PREDICTION VALIDATION
# ======================================================================

def validate_prediction_data(predictions):
    section("PREDICTION DATA STRUCTURE")

    print("Prediction columns:")
    print(list(predictions.columns))

    required = [
        "transaction_id",
        "amount",
    ]

    missing = [c for c in required if c not in predictions.columns]

    if missing:
        failed(
            f"Prediction dataset missing required columns: {missing}"
        )
        sys.exit(1)

    passed("Required prediction columns present")

    if predictions["transaction_id"].duplicated().any():
        failed("Prediction transaction IDs are not unique")
        sys.exit(1)

    passed("Prediction transaction IDs are unique")

    if not pd.to_numeric(
        predictions["amount"], errors="coerce"
    ).notna().all():
        failed("Prediction amounts contain invalid values")
        sys.exit(1)

    if (
        pd.to_numeric(predictions["amount"], errors="coerce") <= 0
    ).any():
        failed("Prediction amounts must be positive")
        sys.exit(1)

    passed("Prediction transaction amounts valid")

    probability_candidates = [
        "calibrated_probability",
        "recovery_probability",
        "base_recovery_probability",
    ]

    probability_column = None

    for column in probability_candidates:
        if column in predictions.columns:
            probability_column = column
            break

    if probability_column is None:
        warning("No recovery probability column found")
    else:
        probabilities = pd.to_numeric(
            predictions[probability_column],
            errors="coerce",
        )

        if probabilities.isna().any():
            failed(
                f"Probability column `{probability_column}` "
                "contains invalid values"
            )
            sys.exit(1)

        if ((probabilities < 0) | (probabilities > 1)).any():
            failed(
                f"Probability column `{probability_column}` "
                "contains values outside [0, 1]"
            )
            sys.exit(1)

        passed(
            f"Recovery probability column valid: "
            f"`{probability_column}`"
        )

    return probability_column


# ======================================================================
# EXPERIMENT STRUCTURE
# ======================================================================

def inspect_experiment_structure(experiment):
    section("TREATMENT / CONTROL EXPERIMENT STRUCTURE")

    print("Experiment columns:")
    print(list(experiment.columns))

    required = [
        "transaction_id",
        "treatment",
        "recovered",
        "recovered_amount",
        "intervention_cost",
        "customer_friction_cost",
        "net_recovered_value",
    ]

    missing = [
        column
        for column in required
        if column not in experiment.columns
    ]

    if missing:
        failed(
            "Experiment dataset is missing required columns:\n"
            + ", ".join(missing)
        )
        sys.exit(1)

    passed("All required treatment/control columns present")

    return required


# ======================================================================
# TRANSACTION VALIDATION
# ======================================================================

def validate_transaction_ids(predictions, experiment):
    section("TRANSACTION POPULATION VALIDATION")

    prediction_ids = set(
        predictions["transaction_id"].astype(str)
    )

    experiment_ids = set(
        experiment["transaction_id"].astype(str)
    )

    missing_in_experiment = prediction_ids - experiment_ids
    extra_in_experiment = experiment_ids - prediction_ids

    print(f"Prediction population: {len(prediction_ids)}")
    print(f"Experiment population: {len(experiment_ids)}")
    print(
        f"Missing in experiment:  {len(missing_in_experiment)}"
    )
    print(
        f"Extra in experiment:    {len(extra_in_experiment)}"
    )

    if missing_in_experiment:
        failed(
            "Some prediction transactions are missing from "
            "the experiment dataset."
        )

        print(
            "First missing IDs:",
            list(missing_in_experiment)[:10]
        )

        sys.exit(1)

    if extra_in_experiment:
        warning(
            f"Experiment contains {len(extra_in_experiment)} "
            "transactions not present in predictions."
        )

        # This is not automatically fatal.
        # The experiment can be restricted to the prediction population.
        experiment = experiment[
            experiment["transaction_id"]
            .astype(str)
            .isin(prediction_ids)
        ].copy()

        passed(
            "Experiment population restricted to prediction population"
        )
    else:
        passed("Same transaction population")

    return experiment


# ======================================================================
# TREATMENT VALIDATION
# ======================================================================

def validate_treatment(experiment):
    section("TREATMENT / CONTROL VALIDATION")

    treatment = pd.to_numeric(
        experiment["treatment"],
        errors="coerce",
    )

    if treatment.isna().any():
        failed("Treatment column contains null/invalid values")
        sys.exit(1)

    unique_values = sorted(treatment.unique().tolist())

    print(f"Treatment values detected: {unique_values}")

    if not set(unique_values).issubset({0, 1}):
        failed(
            "Treatment column must contain only 0 and 1."
        )
        sys.exit(1)

    passed("Treatment values valid")

    treatment_count = int((treatment == 1).sum())
    control_count = int((treatment == 0).sum())

    print()
    print(f"Treatment rows: {treatment_count}")
    print(f"Control rows:   {control_count}")

    if treatment_count == 0:
        failed("No treatment rows found")
        sys.exit(1)

    if control_count == 0:
        failed("No control rows found")
        sys.exit(1)

    passed("Both treatment and control groups present")

    rate = treatment.mean()

    print(f"Treatment allocation: {rate:.2%}")

    if rate < 0.05 or rate > 0.95:
        warning(
            "Treatment allocation is highly imbalanced."
        )
    else:
        passed("Treatment/control allocation is usable")

    return treatment


# ======================================================================
# OUTCOME VALIDATION
# ======================================================================

def validate_outcomes(experiment):
    section("RECOVERY OUTCOME VALIDATION")

    numeric_columns = [
        "recovered",
        "recovered_amount",
        "intervention_cost",
        "customer_friction_cost",
        "net_recovered_value",
    ]

    for column in numeric_columns:
        values = pd.to_numeric(
            experiment[column],
            errors="coerce",
        )

        if values.isna().any():
            failed(
                f"`{column}` contains invalid/null values"
            )
            sys.exit(1)

        passed(f"`{column}` valid")

    recovered = pd.to_numeric(
        experiment["recovered"],
        errors="coerce",
    )

    if not set(recovered.unique()).issubset({0, 1}):
        failed(
            "`recovered` must contain only 0 and 1."
        )
        sys.exit(1)

    passed("Recovery flags valid")

    recovered_amount = pd.to_numeric(
        experiment["recovered_amount"],
        errors="coerce",
    )

    if (recovered_amount < 0).any():
        failed(
            "`recovered_amount` contains negative values"
        )
        sys.exit(1)

    passed("Recovered amounts valid")

    intervention_cost = pd.to_numeric(
        experiment["intervention_cost"],
        errors="coerce",
    )

    if (intervention_cost < 0).any():
        failed(
            "`intervention_cost` contains negative values"
        )
        sys.exit(1)

    passed("Intervention costs valid")

    friction = pd.to_numeric(
        experiment["customer_friction_cost"],
        errors="coerce",
    )

    if (friction < 0).any():
        failed(
            "`customer_friction_cost` contains negative values"
        )
        sys.exit(1)

    passed("Customer friction costs valid")

    # Check consistency between treatment and intervention cost.
    treatment = pd.to_numeric(
        experiment["treatment"],
        errors="coerce",
    )

    untreated_with_cost = experiment.loc[
        treatment == 0,
        "intervention_cost"
    ]

    if (untreated_with_cost > 1e-9).any():
        warning(
            "Some control rows contain intervention cost."
        )
    else:
        passed(
            "Control rows have zero intervention cost"
        )

    treated_without_cost = experiment.loc[
        treatment == 1,
        "intervention_cost"
    ]

    if (treated_without_cost <= 0).any():
        warning(
            "Some treatment rows have zero intervention cost."
        )
    else:
        passed(
            "Treatment rows have positive intervention cost"
        )


# ======================================================================
# TRANSACTION UNIQUE CHECK
# ======================================================================

def validate_unique_transactions(experiment):
    section("TRANSACTION UNIQUENESS")

    if experiment["transaction_id"].duplicated().any():
        duplicates = experiment.loc[
            experiment["transaction_id"].duplicated(keep=False),
            "transaction_id",
        ].unique()

        failed(
            f"Duplicate transaction IDs found: "
            f"{len(duplicates)}"
        )

        print(
            "Example duplicates:",
            list(duplicates)[:10]
        )

        sys.exit(1)

    passed("Experiment transaction IDs are unique")


# ======================================================================
# TREATMENT / CONTROL BALANCE
# ======================================================================

def balance_check(experiment):
    section("TREATMENT / CONTROL BALANCE CHECK")

    treatment = experiment[
        experiment["treatment"] == 1
    ].copy()

    control = experiment[
        experiment["treatment"] == 0
    ].copy()

    balance_features = [
        "amount",
        "recovery_probability",
        "calibrated_probability",
        "confidence",
        "base_recovery_probability",
        "recoverability_score",
    ]

    available = [
        feature
        for feature in balance_features
        if feature in experiment.columns
    ]

    if not available:
        warning(
            "No numeric balance features available."
        )
        return

    print(
        f"{'feature':<32}"
        f"{'treatment mean':>18}"
        f"{'control mean':>18}"
    )
    print("-" * 68)

    for feature in available:
        treatment_values = pd.to_numeric(
            treatment[feature],
            errors="coerce",
        )

        control_values = pd.to_numeric(
            control[feature],
            errors="coerce",
        )

        treatment_mean = treatment_values.mean()
        control_mean = control_values.mean()

        print(
            f"{feature:<32}"
            f"{treatment_mean:>18.4f}"
            f"{control_mean:>18.4f}"
        )

    passed(
        "Treatment/control balance information calculated"
    )


# ======================================================================
# RECOVERY EFFECT
# ======================================================================

def calculate_recovery_effect(experiment):
    section("OBSERVED RECOVERY EFFECT")

    treatment = experiment[
        experiment["treatment"] == 1
    ]

    control = experiment[
        experiment["treatment"] == 0
    ]

    treatment_rate = treatment["recovered"].mean()
    control_rate = control["recovered"].mean()

    lift = treatment_rate - control_rate

    print(
        f"Treatment recovery rate: "
        f"{pct(treatment_rate)}"
    )

    print(
        f"Control recovery rate:   "
        f"{pct(control_rate)}"
    )

    print(
        f"Observed recovery lift:  "
        f"{lift:+.2%}"
    )

    print(
        f"Observed recovery lift:  "
        f"{lift * 100:+.2f} percentage points"
    )

    return treatment_rate, control_rate, lift


# ======================================================================
# ECONOMIC EFFECT
# ======================================================================

def calculate_economic_effect(experiment):
    section("OBSERVED ECONOMIC EFFECT")

    treatment = experiment[
        experiment["treatment"] == 1
    ]

    control = experiment[
        experiment["treatment"] == 0
    ]

    treatment_recovered = treatment[
        "recovered_amount"
    ].sum()

    control_recovered = control[
        "recovered_amount"
    ].sum()

    treatment_cost = treatment[
        "intervention_cost"
    ].sum()

    treatment_friction = treatment[
        "customer_friction_cost"
    ].sum()

    treatment_net = treatment[
        "net_recovered_value"
    ].sum()

    control_net = control[
        "net_recovered_value"
    ].sum()

    treatment_mean_net = treatment_net / len(treatment)
    control_mean_net = control_net / len(control)

    incremental_per_transaction = (
        treatment_mean_net - control_mean_net
    )

    print(
        f"Treatment recovered value: "
        f"{currency(treatment_recovered)}"
    )

    print(
        f"Control recovered value:   "
        f"{currency(control_recovered)}"
    )

    print()

    print(
        f"Treatment intervention cost: "
        f"{currency(treatment_cost)}"
    )

    print(
        f"Treatment friction cost:     "
        f"{currency(treatment_friction)}"
    )

    print()

    print(
        f"Treatment net value: "
        f"{currency(treatment_net)}"
    )

    print(
        f"Control net value:   "
        f"{currency(control_net)}"
    )

    print()

    print(
        "Observed incremental net value / transaction: "
        f"{currency(incremental_per_transaction)}"
    )

    if incremental_per_transaction > 0:
        passed(
            "Treatment produces positive observed "
            "incremental economic value."
        )
    else:
        warning(
            "Treatment does NOT produce positive observed "
            "incremental economic value in this experiment."
        )

    return incremental_per_transaction


# ======================================================================
# COUNTERFACTUAL COLUMNS
# ======================================================================

def inspect_counterfactuals(experiment):
    section("COUNTERFACTUAL / DATA-GENERATING PROCESS CHECK")

    counterfactual_candidates = [
        "control_recovery_probability",
        "treatment_recovery_probability",
        "incremental_recovery_probability",
        "expected_control_recovery",
        "expected_treatment_recovery",
        "expected_incremental_recovery",
        "expected_incremental_net_value",
        "treatment_effect",
    ]

    available = [
        column
        for column in counterfactual_candidates
        if column in experiment.columns
    ]

    if available:
        passed(
            f"Counterfactual/effect columns available: "
            f"{len(available)}"
        )

        for column in available:
            print(f"  [YES] {column}")
    else:
        warning(
            "No explicit counterfactual columns found."
        )

        print(
            "Observed randomized treatment/control data is still "
            "usable for uplift modeling."
        )


# ======================================================================
# TREATMENT ASSIGNMENT TIMING
# ======================================================================

def validate_assignment_metadata(experiment):
    section("TREATMENT ASSIGNMENT TIMING")

    timing_candidates = [
        "treatment_assigned_before_outcome",
        "assignment_before_outcome",
        "treatment_assignment_before_outcome",
        "experiment_valid",
    ]

    available = [
        column
        for column in timing_candidates
        if column in experiment.columns
    ]

    if not available:
        warning(
            "No explicit assignment-timing metadata column found."
        )

        print(
            "The dataset structure is compatible with a randomized "
            "experiment, but timing cannot be independently proven "
            "from the CSV alone."
        )

        return False

    for column in available:
        values = experiment[column]

        normalized = (
            values.astype(str)
            .str.strip()
            .str.lower()
        )

        true_values = {
            "true",
            "1",
            "yes",
            "y",
            "pass",
            "passed",
        }

        if normalized.isin(true_values).all():
            passed(
                f"`{column}` confirms assignment occurred "
                "before outcome generation"
            )
            return True

    warning(
        "Assignment timing metadata exists but does not "
        "confirm pre-outcome assignment."
    )

    return False


# ======================================================================
# FEATURE AVAILABILITY
# ======================================================================

def feature_availability(experiment):
    section("FEATURE AVAILABILITY FOR UPLIFT MODELING")

    available = [
        feature
        for feature in FEATURES
        if feature in experiment.columns
    ]

    missing = [
        feature
        for feature in FEATURES
        if feature not in experiment.columns
    ]

    print(f"Useful features available: {len(available)}")
    print(f"Useful features missing:    {len(missing)}")

    print()

    for feature in FEATURES:
        if feature in experiment.columns:
            print(f"  [YES] {feature}")
        else:
            print(f"  [NO ] {feature}")

    if len(available) >= 5:
        passed(
            "Sufficient transaction-level features appear "
            "available for uplift modeling."
        )
    else:
        warning(
            "Very few modeling features are available."
        )

    return available, missing


# ======================================================================
# FINAL READINESS DECISION
# ======================================================================

def final_readiness_decision(
    experiment,
    timing_verified,
):
    section("FINAL UPLIFT DATA READINESS DECISION")

    treatment = experiment["treatment"]

    treatment_count = int((treatment == 1).sum())
    control_count = int((treatment == 0).sum())

    required_columns = [
        "transaction_id",
        "treatment",
        "recovered",
        "recovered_amount",
        "intervention_cost",
        "customer_friction_cost",
        "net_recovered_value",
    ]

    all_required = all(
        column in experiment.columns
        for column in required_columns
    )

    unique_ids = (
        experiment["transaction_id"].is_unique
    )

    valid_treatment = set(
        pd.to_numeric(
            experiment["treatment"],
            errors="coerce",
        ).dropna().unique()
    ).issubset({0, 1})

    both_groups = (
        treatment_count > 0
        and control_count > 0
    )

    if all_required:
        passed("Required causal experiment columns present")
    else:
        failed(
            "Required causal experiment columns missing"
        )

    if unique_ids:
        passed("Transaction IDs unique")
    else:
        failed("Transaction IDs are not unique")

    if valid_treatment:
        passed("Treatment values are valid")
    else:
        failed("Treatment values are invalid")

    if both_groups:
        passed("Treatment and control groups both present")
    else:
        failed("Treatment/control groups incomplete")

    if timing_verified:
        passed(
            "Treatment assignment timing explicitly verified"
        )
    else:
        warning(
            "Treatment assignment timing is not explicitly "
            "verified from metadata."
        )

    print()
    print("-" * 70)

    # IMPORTANT:
    #
    # We should NOT make timing metadata a hard requirement because
    # the simulator itself generated this dataset. The audit can verify
    # the structural properties while warning if metadata is absent.

    ready = (
        all_required
        and unique_ids
        and valid_treatment
        and both_groups
        and len(experiment) >= 100
    )

    if ready:
        print(
            "[PASS] Valid treatment/control experiment detected."
        )

        print()
        print(
            "The dataset is suitable for causal uplift modeling."
        )

        print()
        print(
            "UPLIFT READINESS: READY"
        )
    else:
        print(
            "[WARN] Treatment/control experiment is not "
            "sufficient for causal uplift modeling."
        )

        print()
        print(
            "UPLIFT READINESS: NOT READY"
        )

    return ready


# ======================================================================
# SAVE AUDIT SUMMARY
# ======================================================================

def save_audit_summary(
    experiment,
    treatment_rate,
    control_rate,
    recovery_lift,
    incremental_net_value,
    ready,
):
    output_file = DATA_DIR / "treatment_control_audit_summary.csv"

    treatment = experiment[
        experiment["treatment"] == 1
    ]

    control = experiment[
        experiment["treatment"] == 0
    ]

    summary = pd.DataFrame(
        [
            {
                "total_transactions": len(experiment),
                "treatment_rows": len(treatment),
                "control_rows": len(control),
                "treatment_rate": treatment.mean().get(
                    "recovered", np.nan
                )
                if False
                else len(treatment) / len(experiment),
                "treatment_recovery_rate": treatment_rate,
                "control_recovery_rate": control_rate,
                "observed_recovery_lift": recovery_lift,
                "treatment_recovered_value":
                    treatment["recovered_amount"].sum(),
                "control_recovered_value":
                    control["recovered_amount"].sum(),
                "treatment_net_value":
                    treatment["net_recovered_value"].sum(),
                "control_net_value":
                    control["net_recovered_value"].sum(),
                "incremental_net_value_per_transaction":
                    incremental_net_value,
                "uplift_ready": ready,
            }
        ]
    )

    summary.to_csv(
        output_file,
        index=False,
    )

    passed(
        f"Saved audit summary: {output_file}"
    )


# ======================================================================
# MAIN
# ======================================================================

def main():
    header("RECLAIM TREATMENT / CONTROL DATA AUDIT")

    print(
        "This audit validates the treatment/control experiment "
        "generated BEFORE recovery outcomes."
    )

    predictions, experiment = load_data()

    probability_column = validate_prediction_data(
        predictions
    )

    inspect_experiment_structure(
        experiment
    )

    experiment = validate_transaction_ids(
        predictions,
        experiment,
    )

    validate_unique_transactions(
        experiment
    )

    validate_treatment(
        experiment
    )

    validate_outcomes(
        experiment
    )

    timing_verified = validate_assignment_metadata(
        experiment
    )

    feature_availability(
        experiment
    )

    inspect_counterfactuals(
        experiment
    )

    treatment_rate, control_rate, recovery_lift = (
        calculate_recovery_effect(experiment)
    )

    incremental_net_value = calculate_economic_effect(
        experiment
    )

    ready = final_readiness_decision(
        experiment,
        timing_verified,
    )

    save_audit_summary(
        experiment,
        treatment_rate,
        control_rate,
        recovery_lift,
        incremental_net_value,
        ready,
    )

    section("AUDIT SUMMARY")

    print(
        f"Prediction rows:       {len(predictions)}"
    )

    print(
        f"Experiment rows:       {len(experiment)}"
    )

    print(
        f"Treatment rows:        "
        f"{int((experiment['treatment'] == 1).sum())}"
    )

    print(
        f"Control rows:          "
        f"{int((experiment['treatment'] == 0).sum())}"
    )

    print(
        f"Observed recovery lift: "
        f"{recovery_lift:+.2%}"
    )

    print(
        "Incremental net value / transaction: "
        f"{currency(incremental_net_value)}"
    )

    print()

    if ready:
        print(
            "UPLIFT READINESS: READY"
        )

        print()
        print(
            "NEXT STEP:"
        )

        print(
            "Build the causal uplift model using:"
        )

        print(
            "  treatment = 1 -> RECLAIM intervention"
        )

        print(
            "  treatment = 0 -> control"
        )

        print(
            "  recovered -> observed outcome"
        )

        print(
            "The model should estimate which transactions "
            "benefit from RECLAIM intervention."
        )

    else:
        print(
            "UPLIFT READINESS: NOT READY"
        )

    section(
        "RECLAIM TREATMENT / CONTROL AUDIT COMPLETE"
    )

    if ready:
        print(
            "STATUS: READY FOR UPLIFT MODELING"
        )
    else:
        print(
            "STATUS: EXPERIMENT DATA REQUIRES CORRECTION"
        )


# ======================================================================
# ENTRY POINT
# ======================================================================

if __name__ == "__main__":
    main()